[[constraint]]
  name = "github.com/Masterminds/semver"
  branch = "2.x"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "1.11.0"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jmank88/nuts"
  version = "0.3.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
[alias]
golang.org/x/blog= github.com/golang/blog
golang.org/x/crypto= github.com/golang/crypto
golang.org/x/exp= github.com/golang/exp
golang.org/x/image= github.com/golang/image
golang.org/x/mobile= github.com/golang/mobile
golang.org/x/net= github.com/golang/net
golang.org/x/sys= github.com/golang/sys
golang.org/x/talks= github.com/golang/talks
golang.org/x/text= github.com/golang/text
golang.org/x/tools= github.com/golang/tools
golang.org/x/sync= github.com/golang/sync
google.golang.org/grpc= github.com/grpc/grpc-go
google.golang.org/genproto= github.com/google/go-genproto